<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Hotel extends \App\Entity\Hotel implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Hotel' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Hotel' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\Hotel' . "\0" . 'adresse1', '' . "\0" . 'App\\Entity\\Hotel' . "\0" . 'adresse2', '' . "\0" . 'App\\Entity\\Hotel' . "\0" . 'cp', '' . "\0" . 'App\\Entity\\Hotel' . "\0" . 'ville', '' . "\0" . 'App\\Entity\\Hotel' . "\0" . 'tel', '' . "\0" . 'App\\Entity\\Hotel' . "\0" . 'mail', '' . "\0" . 'App\\Entity\\Hotel' . "\0" . 'nuites', '' . "\0" . 'App\\Entity\\Hotel' . "\0" . 'tarifs'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Hotel' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Hotel' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\Hotel' . "\0" . 'adresse1', '' . "\0" . 'App\\Entity\\Hotel' . "\0" . 'adresse2', '' . "\0" . 'App\\Entity\\Hotel' . "\0" . 'cp', '' . "\0" . 'App\\Entity\\Hotel' . "\0" . 'ville', '' . "\0" . 'App\\Entity\\Hotel' . "\0" . 'tel', '' . "\0" . 'App\\Entity\\Hotel' . "\0" . 'mail', '' . "\0" . 'App\\Entity\\Hotel' . "\0" . 'nuites', '' . "\0" . 'App\\Entity\\Hotel' . "\0" . 'tarifs'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Hotel $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom(string $nom): \App\Entity\Hotel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse1(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse1', []);

        return parent::getAdresse1();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse1(string $adresse1): \App\Entity\Hotel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse1', [$adresse1]);

        return parent::setAdresse1($adresse1);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse2(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse2', []);

        return parent::getAdresse2();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse2(?string $adresse2): \App\Entity\Hotel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse2', [$adresse2]);

        return parent::setAdresse2($adresse2);
    }

    /**
     * {@inheritDoc}
     */
    public function getCp(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCp', []);

        return parent::getCp();
    }

    /**
     * {@inheritDoc}
     */
    public function setCp(string $cp): \App\Entity\Hotel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCp', [$cp]);

        return parent::setCp($cp);
    }

    /**
     * {@inheritDoc}
     */
    public function getVille(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVille', []);

        return parent::getVille();
    }

    /**
     * {@inheritDoc}
     */
    public function setVille(string $ville): \App\Entity\Hotel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVille', [$ville]);

        return parent::setVille($ville);
    }

    /**
     * {@inheritDoc}
     */
    public function getTel(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTel', []);

        return parent::getTel();
    }

    /**
     * {@inheritDoc}
     */
    public function setTel(string $tel): \App\Entity\Hotel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTel', [$tel]);

        return parent::setTel($tel);
    }

    /**
     * {@inheritDoc}
     */
    public function getMail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMail', []);

        return parent::getMail();
    }

    /**
     * {@inheritDoc}
     */
    public function setMail(string $mail): \App\Entity\Hotel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMail', [$mail]);

        return parent::setMail($mail);
    }

    /**
     * {@inheritDoc}
     */
    public function getNuites(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNuites', []);

        return parent::getNuites();
    }

    /**
     * {@inheritDoc}
     */
    public function addNuite(\App\Entity\Nuite $nuite): \App\Entity\Hotel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addNuite', [$nuite]);

        return parent::addNuite($nuite);
    }

    /**
     * {@inheritDoc}
     */
    public function removeNuite(\App\Entity\Nuite $nuite): \App\Entity\Hotel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeNuite', [$nuite]);

        return parent::removeNuite($nuite);
    }

    /**
     * {@inheritDoc}
     */
    public function getTarifs(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTarifs', []);

        return parent::getTarifs();
    }

    /**
     * {@inheritDoc}
     */
    public function addTarif(\App\Entity\Proposer $tarif): \App\Entity\Hotel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTarif', [$tarif]);

        return parent::addTarif($tarif);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTarif(\App\Entity\Proposer $tarif): \App\Entity\Hotel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTarif', [$tarif]);

        return parent::removeTarif($tarif);
    }

}
