<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CategorieChambre extends \App\Entity\CategorieChambre implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\CategorieChambre' . "\0" . 'id', '' . "\0" . 'App\\Entity\\CategorieChambre' . "\0" . 'libelleCategorie', '' . "\0" . 'App\\Entity\\CategorieChambre' . "\0" . 'nuites', '' . "\0" . 'App\\Entity\\CategorieChambre' . "\0" . 'tarifs'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\CategorieChambre' . "\0" . 'id', '' . "\0" . 'App\\Entity\\CategorieChambre' . "\0" . 'libelleCategorie', '' . "\0" . 'App\\Entity\\CategorieChambre' . "\0" . 'nuites', '' . "\0" . 'App\\Entity\\CategorieChambre' . "\0" . 'tarifs'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CategorieChambre $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getLibelleCategorie(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLibelleCategorie', []);

        return parent::getLibelleCategorie();
    }

    /**
     * {@inheritDoc}
     */
    public function setLibelleCategorie(string $libelleCategorie): \App\Entity\CategorieChambre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLibelleCategorie', [$libelleCategorie]);

        return parent::setLibelleCategorie($libelleCategorie);
    }

    /**
     * {@inheritDoc}
     */
    public function getNuites(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNuites', []);

        return parent::getNuites();
    }

    /**
     * {@inheritDoc}
     */
    public function addNuite(\App\Entity\Nuite $nuite): \App\Entity\CategorieChambre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addNuite', [$nuite]);

        return parent::addNuite($nuite);
    }

    /**
     * {@inheritDoc}
     */
    public function removeNuite(\App\Entity\Nuite $nuite): \App\Entity\CategorieChambre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeNuite', [$nuite]);

        return parent::removeNuite($nuite);
    }

    /**
     * {@inheritDoc}
     */
    public function getTarifs(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTarifs', []);

        return parent::getTarifs();
    }

    /**
     * {@inheritDoc}
     */
    public function addTarif(\App\Entity\Proposer $tarif): \App\Entity\CategorieChambre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTarif', [$tarif]);

        return parent::addTarif($tarif);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTarif(\App\Entity\Proposer $tarif): \App\Entity\CategorieChambre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTarif', [$tarif]);

        return parent::removeTarif($tarif);
    }

}
