<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSEWEIhL\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSEWEIhL/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSEWEIhL.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSEWEIhL\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerSEWEIhL\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'SEWEIhL',
    'container.build_id' => 'da4ea821',
    'container.build_time' => 1651219187,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSEWEIhL');
