<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKSxJ1LC\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKSxJ1LC/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKSxJ1LC.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKSxJ1LC\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKSxJ1LC\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'KSxJ1LC',
    'container.build_id' => '52680dd5',
    'container.build_time' => 1648811457,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKSxJ1LC');
