<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZOGHaKe\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZOGHaKe/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZOGHaKe.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZOGHaKe\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZOGHaKe\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ZOGHaKe',
    'container.build_id' => '97e2dd41',
    'container.build_time' => 1651647148,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZOGHaKe');
